### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by samboman** [chuckcharlie/cups-avahi-airprint#37]
I run docker on Ubuntu. I end up in a restart loop with this basic setup.

My goal is to expose mu old network-printer as an AirPrint device. I have cups on an old VM with it working with my printer. But this is just a new setup. `/services` and `/config` are empty from scratch (eg, I have not configured anything yet).

Thanks!

Docker compose:
```
services:
  cups:
    image: chuckcharlie/cups-avahi-airprint:latest
    container_name: cups
    restart: unless-stopped
    network_mode: host
    environment:
      - CUPSADMIN=admin
      - CUPSPASSWORD=secretPassW0rd
    volumes:
      - /opt/docker/cups/services:/services
      - /opt/docker/cups/config:/config
``` 

Docker log:
```
...
Setting up watches.
Watches established.
+ '[' -z admin ]
+ '[' -z secretPassW0rd ]
+ grep -ci admin /etc/shadow
+ '[' 1 -eq 0 ]
+ echo admin:secretPassW0rd
+ chpasswd
chpasswd: password for 'admin' changed
+ mkdir -p /config/ppd
+ mkdir -p /services
+ rm -rf '/etc/avahi/services/*'
+ rm -rf /etc/cups/ppd
+ ln -s /config/ppd /etc/cups
+ ls -l '/services/*.service'
+ wc -l
+ '[' 0 -gt 0 ]
+ ls -l /config/printers.conf
+ wc -l
+ '[' 1 -eq 0 ]
+ cp /config/printers.conf /etc/cups/printers.conf
+ ls -l /config/cupsd.conf
+ wc -l
+ '[' 0 -ne 0 ]
+ /usr/sbin/avahi-daemon --daemonize
Process 27 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)
+ /root/printer-update.sh
+ exec /usr/sbin/cupsd -f
Setting up watches.
Watches established.
+ '[' -z admin ]
+ '[' -z secretPassW0rd ]
+ grep -ci admin /etc/shadow
+ '[' 1 -eq 0 ]
+ echo admin:secretPassW0rd
+ chpasswd
chpasswd: password for 'admin' changed
+ mkdir -p /config/ppd
+ mkdir -p /services
+ rm -rf '/etc/avahi/services/*'
+ rm -rf /etc/cups/ppd
+ ln -s /config/ppd /etc/cups
+ ls -l '/services/*.service'
+ wc -l
+ '[' 0 -gt 0 ]
+ ls -l /config/printers.conf
+ wc -l
+ '[' 1 -eq 0 ]
+ cp /config/printers.conf /etc/cups/printers.conf
+ ls -l /config/cupsd.conf
+ wc -l
+ '[' 0 -ne 0 ]
+ /usr/sbin/avahi-daemon --daemonize
Process 27 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)
+ exec /usr/sbin/cupsd -f
+ /root/printer-update.sh
Setting up watches.
Watches established.
...
```
